name: Deploy Site
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get Source
        uses: actions/checkout@v2
        with:
          path: statiqdev.github.io
          submodules: recursive
      - name: Checkout Statiq.Framework
        uses: actions/checkout@v2
        with:
          repository: statiqdev/Statiq.Framework
          path: Statiq.Framework
          submodules: recursive
      - name: Checkout Statiq.Web
        uses: actions/checkout@v2
        with:
          repository: statiqdev/Statiq.Web
          path: Statiq.Web
          submodules: recursive
      - name: Checkout Statiq.Docs
        uses: actions/checkout@v2
        with:
          repository: statiqdev/Statiq.Docs
          path: Statiq.Docs
          submodules: recursive
      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            6.0.x
      - run: dotnet run -- deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}